import { notFound } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import type { Lead } from '@/lib/types'
import { LeadEditor } from '@/components/admin/lead-editor'

export default async function LeadDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const db = await createClient(); if (!db) notFound()
  const [{ data }, { data: activity }] = await Promise.all([db.from('leads').select('*').eq('id',id).single(), db.from('lead_activity').select('*').eq('lead_id',id).order('created_at',{ascending:false})])
  if (!data) notFound(); const lead=data as Lead; const digits=lead.phone.replace(/\D/g,'');
  return <div><p className="text-sm font-semibold text-blue-600">{lead.order_number}</p><h1 className="mt-1 text-3xl font-bold">{lead.name}</h1><div className="mt-6 grid gap-6 xl:grid-cols-[1fr_380px]"><div className="space-y-6"><Section title="Datos del cliente"><Info label="Correo" value={lead.email}/><Info label="Teléfono" value={lead.phone}/><Info label="Dirección" value={lead.address}/></Section><Section title="Solicitud"><Info label="Servicio" value={lead.service_type}/><Info label="Urgencia" value={lead.urgency}/><div className="col-span-full rounded-xl bg-slate-50 p-4 text-sm whitespace-pre-wrap">{lead.description}</div></Section><Section title="Origen"><Info label="Fuente / medio" value={[lead.source,lead.medium].filter(Boolean).join(' / ')||'Directo'}/><Info label="Campaña" value={lead.campaign||'—'}/><Info label="Término" value={lead.term||'—'}/><Info label="Contenido" value={lead.content||'—'}/><Info label="GCLID" value={lead.gclid||'—'}/><Info label="Landing" value={lead.landing_page||'—'}/></Section><Section title="Historial"><div className="col-span-full space-y-3">{(activity??[]).map((item:any)=><div key={item.id} className="border-l-2 border-blue-500 pl-4 text-sm"><strong>{item.activity_type}</strong><p className="text-slate-500">{new Intl.DateTimeFormat('es-CL',{dateStyle:'medium',timeStyle:'short'}).format(new Date(item.created_at))}</p>{item.details?.note&&<p className="mt-1">{item.details.note}</p>}</div>)}{!(activity??[]).length&&<p className="text-sm text-slate-500">Sin actividad registrada.</p>}</div></Section></div><aside className="space-y-4"><LeadEditor lead={lead}/><div className="grid grid-cols-3 gap-2"><a target="_blank" rel="noreferrer" href={`https://wa.me/${digits}`} className="rounded-xl border bg-white p-3 text-center text-sm">WhatsApp</a><a href={`mailto:${lead.email}`} className="rounded-xl border bg-white p-3 text-center text-sm">Email</a><a href={`tel:${lead.phone}`} className="rounded-xl border bg-white p-3 text-center text-sm">Llamar</a></div></aside></div></div>
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="grid gap-4 rounded-2xl border bg-white p-6 sm:grid-cols-2"><h2 className="col-span-full font-bold">{title}</h2>{children}</section>}
function Info({label,value}:{label:string;value:string}){return <div><p className="text-xs uppercase text-slate-500">{label}</p><p className="mt-1 break-words text-sm font-medium">{value}</p></div>}

