'use client'
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'

type Daily={date:string;visitors:number;clicks:number;spend:number;quotes:number;revenue:number;roas:number|null;cpa:number|null}
export function DashboardCharts({daily,sources,statuses}:{daily:Daily[];sources:{name:string;value:number}[];statuses:{name:string;value:number}[]}){
  if(!daily.length&&!sources.length)return <div className="rounded-2xl border bg-white p-8 text-center text-slate-500">No hay datos suficientes para graficar este período.</div>
  return <section className="grid gap-6 xl:grid-cols-2"><Chart title="Actividad diaria"><LineChart data={daily}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date"/><YAxis/><Tooltip/><Line type="monotone" dataKey="visitors" name="Visitantes" stroke="#2563eb"/><Line type="monotone" dataKey="clicks" name="Clics Ads" stroke="#06b6d4"/><Line type="monotone" dataKey="quotes" name="Cotizaciones" stroke="#7c3aed"/></LineChart></Chart><Chart title="Inversión y facturación"><BarChart data={daily}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date"/><YAxis/><Tooltip/><Bar dataKey="spend" name="Gasto Ads" fill="#2563eb"/><Bar dataKey="revenue" name="Facturación" fill="#10b981"/></BarChart></Chart><Chart title="Leads por fuente"><BarChart data={sources} layout="vertical"><CartesianGrid strokeDasharray="3 3"/><XAxis type="number"/><YAxis type="category" dataKey="name" width={90}/><Tooltip/><Bar dataKey="value" name="Leads" fill="#0891b2"/></BarChart></Chart><Chart title="Estado de leads"><BarChart data={statuses}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="value" name="Leads" fill="#7c3aed"/></BarChart></Chart></section>
}
function Chart({title,children}:{title:string;children:React.ReactElement}){return <div className="rounded-2xl border bg-white p-5"><h2 className="mb-4 font-bold">{title}</h2><div className="h-72"><ResponsiveContainer width="100%" height="100%">{children}</ResponsiveContainer></div></div>}
