import { getDateRange } from '@/lib/date-range'
import { getGoogleAdsReport } from '@/lib/google-ads'
import { PeriodFilter } from '@/components/admin/period-filter'

const get=(row:Record<string,unknown>,group:string,key:string)=>((row[group] as Record<string,unknown>|undefined)?.[key])
const num=(v:unknown)=>Number(v||0), money=(micros:unknown)=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(num(micros)/1_000_000)
export default async function Campaigns({searchParams}:{searchParams:Promise<{period?:string}>}){const q=await searchParams,range=getDateRange(q.period),report=await getGoogleAdsReport(range.from,range.to);return <div><div className="flex flex-col justify-between gap-4 md:flex-row"><div><p className="text-sm font-semibold text-blue-600">GOOGLE ADS · SOLO LECTURA</p><h1 className="mt-1 text-3xl font-bold">Campañas</h1></div><PeriodFilter/></div><State configured={report.configured} error={report.error}/>{report.configured&&!report.error&&<div className="mt-6 overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[950px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase text-slate-500"><tr>{['Campaña','Tipo','Estado','Presupuesto diario','Impresiones','Clics','CTR','CPC','Costo','Conversiones','CPA'].map(x=><th className="px-4 py-3" key={x}>{x}</th>)}</tr></thead><tbody>{report.campaigns.map((r,i)=><tr key={String(get(r,'campaign','id')||i)} className="border-b"><td className="px-4 py-4 font-semibold">{String(get(r,'campaign','name')||'—')}</td><td className="px-4 py-4">{String(get(r,'campaign','advertisingChannelType')||'—')}</td><td className="px-4 py-4">{String(get(r,'campaign','status')||'—')}</td><td className="px-4 py-4">{money(get(r,'campaignBudget','amountMicros'))}</td><td className="px-4 py-4">{num(get(r,'metrics','impressions')).toLocaleString('es-CL')}</td><td className="px-4 py-4">{num(get(r,'metrics','clicks')).toLocaleString('es-CL')}</td><td className="px-4 py-4">{(num(get(r,'metrics','ctr'))*100).toFixed(2)}%</td><td className="px-4 py-4">{money(get(r,'metrics','averageCpc'))}</td><td className="px-4 py-4">{money(get(r,'metrics','costMicros'))}</td><td className="px-4 py-4">{num(get(r,'metrics','conversions')).toFixed(1)}</td><td className="px-4 py-4">{money(get(r,'metrics','costPerConversion'))}</td></tr>)}</tbody></table>{!report.campaigns.length&&<p className="p-10 text-center text-slate-500">No hay campañas con actividad en el período.</p>}</div>}</div>}
function State({configured,error}:{configured:boolean;error?:string}){if(!configured)return <p className="mt-6 rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-800">Google Ads aún no está configurado. Agrega las variables indicadas en <code>.env.example</code>.</p>;if(error)return <p className="mt-6 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</p>;return null}

